debug = false
defaultEntryPoints = ["http", "https"]

[log]
level = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

# API definition
[api]
  debug = false
  dashboard = false

# Enable retry sending request if network error
[retry]
# Number of attempts
#
# Optional
# Default: (number servers in backend) -1
#
attempts = 3

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "chertopolokh.ru"
watch = true
exposedByDefault = false
swarmMode = false

[acme]
email = "dmitry@romashov.tech"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "chertopolokh.ru"
  sans = ["www.chertopolokh.ru"]